# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7c7b\u578b')),
                ('action_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4e2d\u6587\u63cf\u8ff0')),
                ('backup', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6d4b\u8bd5\u5b57\u6bb5')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True, verbose_name='\u6309\u94ae\u8be6\u60c5')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='\u5237\u65b0\u65f6\u95f4')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='\u5237\u65b0\u6b21\u6570')),
                ('backup', models.TextField(blank=True, null=True, verbose_name='\u6d4b\u8bd5\u5b57\u6bb5')),
            ],
        ),
    ]
