# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
    ]
