# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20170531_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='backup',
        ),
    ]
