# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_remove_actions_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='back',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='back'),
        ),
    ]
