# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_delete_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7c7b\u578b')),
                ('action_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4e2d\u6587\u63cf\u8ff0')),
                ('back', models.CharField(blank=True, max_length=100, null=True, verbose_name='back')),
            ],
        ),
    ]
