# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_actions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'ordering': ('-id',), 'verbose_name': '\u6240\u6709\u52a8\u4f5c', 'verbose_name_plural': '\u6240\u6709\u52a8\u4f5c'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('-id',), 'verbose_name': '\u6309\u94ae\u7ec4', 'verbose_name_plural': '\u6309\u94ae\u7ec4'},
        ),
    ]
