# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0007_auto_20170601_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoXie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u7f16\u53f7')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u540d\u5b57')),
                ('e_mail', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u7535\u5b50\u90ae\u7bb1')),
                ('tel', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u7535\u8bdd')),
                ('fenji', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5206\u673a')),
                ('seat', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5ea7\u4f4d')),
                ('state', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5750\u5e2d')),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': '\u6211\u643a',
                'verbose_name_plural': '\u6211\u643a',
            },
        ),
    ]
