# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_woxie'),
    ]

    operations = [
        migrations.AddField(
            model_name='woxie',
            name='english_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u82f1\u6587\u540d'),
        ),
    ]
