# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0009_woxie_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u4f18\u5148\u7ea7'),
        ),
        migrations.AddField(
            model_name='actions',
            name='rule',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5339\u914d\u89c4\u5219'),
        ),
    ]
