# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0010_auto_20170601_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='HduStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u7f16\u53f7')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u540d\u5b57')),
                ('sex', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u6027\u522b')),
                ('college', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5b66\u9662')),
                ('major', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u4e13\u4e1a')),
                ('grade', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5e74\u7ea7')),
                ('grade_now', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5f53\u524d\u5e74\u7ea7')),
                ('sort', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u7c7b\u522b')),
                ('state', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u662f\u5426\u5728\u6821')),
                ('state_xueji', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5b66\u7c4d\u72b6\u6001')),
                ('idcard', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('home', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u751f\u6e90\u5730')),
                ('nation', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u6c11\u65cf')),
                ('age', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5e74\u9f84')),
                ('month', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u6708\u4efd')),
                ('year', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5e74\u4efd')),
                ('xing', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u59d3\u6c0f')),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': 'Hdu\u5b66\u7c4d',
                'verbose_name_plural': 'Hdu\u5b66\u7c4d',
            },
        ),
    ]
